services:
  - name: docker:dind
    entrypoint: ["env", "-u", "DOCKER_HOST"]
    command: ["dockerd-entrypoint.sh"]

stages:
  - build-dev
  - build
  - test
  - deploy

include:
  - project: 'infralabs/cxaas/sourcecode/commontools/devops'
    file: '/variables.yaml'
  - project: 'infralabs/cxaas/sourcecode/commontools/devops'
    file: '/build_dev.yaml'
  - project: 'infralabs/cxaas/sourcecode/commontools/devops'
    file: '/deploy_aks.yaml'

Build Code:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - export DOCKER_TAG='if [ $CI_COMMIT_BRANCH == 'main' ]; then echo $CI_COMMIT_SHORT_SHA; else echo $CI_COMMIT_TAG; fi;'
    - export SUBSCRIPTION='if [ $CI_COMMIT_BRANCH == 'main' ]; then echo 9b80411a-6b86-4903-b3c3-6de38998eeea; else echo 9b80411a-6b86-4903-b3c3-6de38998eeea; fi;'
    - export RESOURCE='if [ $CI_COMMIT_BRANCH == 'main' ]; then echo rg-containers-hml; else echo rg-containers; fi;'
    - export CLUSTER='if [ $CI_COMMIT_BRANCH == 'main' ]; then echo aks-cxaas-hml; else echo aks-cxaas; fi;'
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
    - cp "${NPMRC_FILE}" >> .npmrc
    - cp "${ENV_FILE}" .env
    - docker build -t ${CI_REGISTRY_IMAGE}:${DOCKER_TAG} .
    - docker push ${CI_REGISTRY_IMAGE}:${DOCKER_TAG}
  only:
    - main
    - tags
  when: manual

Test Coverage:
  stage: test
  script:
    - echo teste
  only:
    - main
  when: manual
