services:
    - name: docker:dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]

stages:
    - qualitycode
    - build
    - deploy

include:
  - project: 'infralabs/infra-shop/cxaas/sourcecode/commontools/devops'
    file: '/variables.yaml'
  - project: 'infralabs/infra-shop/cxaas/sourcecode/commontools/devops'
    file: '/qualitycode.yaml'
  - project: 'infralabs/infra-shop/cxaas/sourcecode/commontools/devops'
    file: '/build_api_node.yaml'
  - project: 'infralabs/infra-shop/cxaas/sourcecode/commontools/devops'
    file: '/deploy_aks.yaml'
