version: "3.7"

services:
  ifc-freight-api-orders:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    networks:
      - cxaas-ecosystem-network

networks:
  cxaas-ecosystem-network:
    external: true
    name: cxaas-ecosystem-network
