name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [pull_request]
jobs:
  sast_scan:
    if: github.event_name == 'pull_request' && github.event.action == 'opened' && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
            ref: ${{ github.sha }}

      - name: Self sast-scan
        uses: AppThreat/sast-scan-action@master
        continue-on-error: true
        with:
          output: reports
          type: nodejs,credscan,depscan
      - name: Upload scan reports
        uses: actions/upload-artifact@v1
        with:
          name: sast-scan-reports
          path: reports
